export type PhraseDef = {
  id: string
  type?: string
  phrase: string[][]
  phonetics: string[]
  definition: string
  explanation: string
}

export const PHRASES: PhraseDef[] = [
  {
    id: '1',
    phrase: [['PIN', 'CHOS']],
    phonetics: ['PEEN', 'CHOS'],
    definition: 'Tapas',
    explanation: 'A small snack, typically eaten in bars with one or two bites',
  },
  {
    id: '2',
    phrase: [['BOT', 'TEL', 'LÓN']],
    phonetics: ['BOH', 'TEH', 'YOHN'],
    definition: 'A Street Party',
    explanation: 'A Spanish activity where a group of people gather in a street to drink',
  },
]

export const DAILYPHRASES: PhraseDef[] = [
  {
    id: 'phrase1',
    type: 'Food',
    phrase: [['Un'], ['En', 'tran', 'te']],
    phonetics: ['uhn', 'ehn', 'trahn', 'teh'],
    definition: 'A starter',
    explanation: "This means 'a starter'",
  },
  {
    id: 'phrase2',
    type: 'Food',
    phrase: [
      ['Se', 'gun', 'do'],
      ['Pla', 'to'],
    ],
    phonetics: ['seh', 'goon', 'doh', 'plah', 'toh'],
    definition: 'Main Meal',
    explanation: "This translates to a 'main meal'",
  },
  {
    id: 'phrase3',
    type: 'Food',
    phrase: [['Be', 'bi', 'das']],
    phonetics: ['beh', 'bee', 'das'],
    definition: 'Drinks',
    explanation: "This is the Spanish word for 'drinks'",
  },
  {
    id: 'phrase4',
    type: 'Food',
    phrase: [['Es'], ['Pi', 'can', 'te']],
    phonetics: ['ehs', 'pee', 'kahn', 'teh'],
    definition: "It's Spicy",
    explanation: "This is a way of saying 'it's spicy'!",
  },
  {
    id: 'phrase5',
    type: 'Food',
    phrase: [['Es'], ['Dul', 'ce']],
    phonetics: ['ehs', 'dool', 'theh'],
    definition: "It's sweet",
    explanation: "This is a way of saying 'it's sweet'!",
  },
  {
    id: 'phrase6',
    type: 'Food',
    phrase: [['Es'], ['Sa', 'la', 'do']],
    phonetics: ['ehs', 'sah', 'lah', 'doh'],
    definition: "It's salty",
    explanation: "This is a way of saying 'it's salty'!",
  },
  {
    id: 'phrase7',
    type: 'Food',
    phrase: [
      ['Es', 'tá'],
      ['ri', 'co'],
    ],
    phonetics: ['ehs', 'tah', 'rree', 'koh'],
    definition: "It's yummy",
    explanation: "This is a way of saying 'it's yummy'!",
  },
  {
    id: 'phrase8',
    type: 'Food',
    phrase: [['Las'], ['ham', 'bur', 'gue', 'sas']],
    phonetics: ['las', 'ahm', 'boor', 'geh', 'sahs'],
    definition: 'Hamburgers',
    explanation: "This is the Spanish word for 'hamburgers'",
  },
  {
    id: 'phrase9',
    type: 'Food',
    phrase: [['Las'], ['pa', 'ta', 'tas', 'fri', 'tas']],
    phonetics: ['las', 'pah', 'tah', 'tahs', 'free', 'tahs'],
    definition: 'French fries',
    explanation: "This one's easy - it means 'french fries'",
  },
  {
    id: 'phrase10',
    type: 'Food',
    phrase: [['El'], ['bo', 'ca', 'di', 'llo']],
    phonetics: ['el', 'boh', 'kah', 'dee', 'yoh'],
    definition: 'A sandwich',
    explanation:
      "This is a type of 'sandwich', typically a baguette style sandwich which is sliced in half lengthways and filled with something like chorizo, cold cuts or serrano ham",
  },
  {
    id: 'phrase11',
    type: 'Food',
    phrase: [['Tos', 'ta'], ['de'], ['a', 'gua', 'ca', 'te']],
    phonetics: ['tohs', 'tah', 'de', 'ah', 'gwah', 'kah', 'teh'],
    definition: 'Avocado toast',
    explanation: "This one translates to 'avocado toast'",
  },
  {
    id: 'phrase12',
    type: 'Food',
    phrase: [
      ['Cre', 'ma'],
      ['Ca', 'ta', 'la', 'na'],
    ],
    phonetics: ['kreh', 'mah', 'kah', 'tah', 'lahna'],
    definition: 'Crème brulée',
    explanation: "The Spanish translation for 'crème brulée'",
  },
  {
    id: 'phrase13',
    type: 'Food',
    phrase: [['Al', 'bón', 'di', 'gas']],
    phonetics: ['ahl', 'bohn', 'dee', 'gahs'],
    definition: 'Meatballs',
    explanation: "Bet you've heard this one before? Albondigas translates to 'meatballs'",
  },
  {
    id: 'phrase15',
    type: 'Food',
    phrase: [['Fi', 'deos']],
    phonetics: ['fee', 'deh', 'ohs'],
    definition: 'Noodles',
    explanation: "Spanish for 'noodles'",
  },
  {
    id: 'phrase16',
    type: 'Food',
    phrase: [['Pe', 'pi', 'ni', 'llos']],
    phonetics: ['perh', 'pee', 'nee', 'yohs'],
    definition: 'Gherkins',
    explanation: "One to remember if you want these taken off your burger! This translates to 'gherkins'",
  },
  {
    id: 'phrase17',
    type: 'Food',
    phrase: [['A', 'hu', 'ma', 'dos']],
    phonetics: ['ah', 'oo', 'mah', 'dohs'],
    definition: 'Smoked foods',
    explanation: "A way of saying 'smoked foods'",
  },
  {
    id: 'phrase18',
    type: 'Music',
    phrase: [['Rit', 'mo']],
    phonetics: ['rreet', 'moh'],
    definition: 'The beat',
    explanation:
      "This one means 'the beat', handy for when you're at a gig or listening to one of our Spotify playlists",
  },
  {
    id: 'phrase19',
    type: 'Music',
    phrase: [['Te', 'ma', 'zo']],
    phonetics: ['teh', 'mah', 'soh'],
    definition: 'Tune/banger',
    explanation: "A way of saying 'tune' or 'banger'! Great for saying to mates whilst you're at a great gig",
  },
  {
    id: 'phrase20',
    type: 'Music',
    phrase: [['Un'], ['bo', 'lo', 'se', 'cre', 'to']],
    phonetics: ['uhn', 'boh', 'loh', 'seh', 'kreh', 'toh'],
    definition: 'A secret gig',
    explanation: "This one translates to 'a secret gig' ??",
  },
  {
    id: 'phrase21',
    type: 'Music',
    phrase: [['Su', 'be'], ['el'], ['vo', 'lu', 'men']],
    phonetics: ['soo', 'beh', 'el', 'boh', 'loo', 'mehn'],
    definition: 'Turn it up!',
    explanation: "A way of saying 'turn it up!' - a handy one to remember!",
  },
  {
    id: 'phrase22',
    type: 'Music',
    phrase: [['Bai', 'lar']],
    phonetics: ['bay', 'lahr'],
    definition: 'To dance',
    explanation: "This translates to 'to dance'",
  },
  {
    id: 'phrase23',
    type: 'Art',
    phrase: [
      ['Ar', 'te'],
      ['Cal', 'le', 'je', 'ro'],
    ],
    phonetics: ['ahr', 'teh', 'kah', 'yeh', 'heh', 'roh'],
    definition: 'Street Art',
    explanation: "This one means 'street art'",
  },
  {
    id: 'phrase24',
    type: 'Art',
    phrase: [
      ['Ar', 'te'],
      ['Ur', 'ba', 'no'],
    ],
    phonetics: ['ahr', 'teh', 'oor', 'bah', 'noh'],
    definition: 'Street Art',
    explanation: "This one means 'street art'",
  },
  {
    id: 'phrase25',
    type: 'Art',
    phrase: [['Ar', 'tis', 'ta']],
    phonetics: ['ahr', 'tees', 'tah'],
    definition: 'Artist',
    explanation: "This one means an 'artist'",
  },
  {
    id: 'phrase26',
    type: 'Art',
    phrase: [['Fo', 'to', 'gra', 'fí', 'a']],
    phonetics: ['foh', 'toh', 'grah', 'fee', 'ah'],
    definition: 'Photography',
    explanation: "No bonus points for getting this one! It means 'photography'",
  },
  {
    id: 'phrase27',
    type: 'Art',
    phrase: [
      ['O', 'bra'],
      ['Ma', 'est', 'ra'],
    ],
    phonetics: ['oh', 'brah', 'mah', 'ehs', 'trah'],
    definition: 'masterpiece',
    explanation: "A phrase for 'a masterpiece'",
  },
  {
    id: 'phrase28',
    type: 'Art',
    phrase: [['Co', 'la', 'bo', 'ra', 'ción']],
    phonetics: ['koh', 'lah', 'boh', 'rah', 'thyohn'],
    definition: 'Collaboration',
    explanation: "Spanish translation for 'collaboration'",
  },
  {
    id: 'phrase29',
    type: 'Beer',
    phrase: [['Cer', 've', 'za']],
    phonetics: ['thehr', 'beh', 'tah'],
    definition: 'beer',
    explanation: "The Spanish word for 'beer'",
  },
  {
    id: 'phrase30',
    type: 'Beer',
    phrase: [
      ['U', 'NA'],
      ['CA', 'ÑA'],
    ],
    phonetics: ['uhn', 'a', 'kah', 'nyah'],
    definition: 'small draught beer',
    explanation:
      "In Spain, the locals like to enjoy their beer as una caña, which essentially is a small draught beer. It's not a full sized pint and is a preference for those enjoying their beer in the sunshine, where the beer could go warm quicker! It's their ' way of keeping their beer cool",
  },
  {
    id: 'phrase31',
    type: 'Beer',
    phrase: [['Bo', 'te', 'lín']],
    phonetics: ['boh', 'teh', 'yin'],
    definition: '20cl bottle of beer',
    explanation: 'A bottelín is a small 20cl bottle of beer - another way to beat the heat and keep their beer cool!',
  },
  {
    id: 'phrase32',
    type: 'Beer',
    phrase: [['Ter', 'cio']],
    phonetics: ['tehr', 'thyoh'],
    definition: '33cl bottle of beer',
    explanation: 'A tercio is a 33cl sbottle of beer',
  },
  {
    id: 'phrase33',
    type: 'Beer',
    phrase: [
      ['U', 'na'],
      ['me', 'dia'],
    ],
    phonetics: ['uhn', 'a', 'meh', 'dyah'],
    definition: 'A bottled beer',
    explanation: "A way of saying 'bottled beer'",
  },
  {
    id: 'phrase34',
    type: 'Beer',
    phrase: [['Do', 'ble']],
    phonetics: ['doh', 'bleh'],
    definition: 'Draught beer (double the size of una CAÑA)',
    explanation: 'This one is for a draught beer, one that is typically double the size of una caña',
  },
  {
    id: 'phrase35',
    type: 'Beer',
    phrase: [['JAR', 'RA']],
    phonetics: ['hah', 'rrah'],
    definition: 'at least equal to a pint and generally the largest draft beer sold',
    explanation:
      "A jarra is a draught beer that is at least equal to a pint - it's generally the largest draft beer sold in Spain",
  },
  {
    id: 'phrase36',
    type: 'Generic',
    phrase: [['¡Mo', 'la!']],
    phonetics: ['moh', 'lah'],
    definition: 'cool!',
    explanation: "A casual way of saying 'cool!'",
  },
  {
    id: 'phrase37',
    type: 'Generic',
    phrase: [['¡Sa', 'lud!']],
    phonetics: ['sah', 'lood'],
    definition: 'cheers!',
    explanation: "This is one of our favourites - it's how the Spanish say 'cheers!'",
  },
  {
    id: 'phrase38',
    type: 'Generic',
    phrase: [['¡Fe', 'tén!']],
    phonetics: ['feh', 'ten'],
    definition: 'great!',
    explanation: "A way to say 'great!'",
  },
  {
    id: 'phrase39',
    type: 'Generic',
    phrase: [['¿Qué'], ['pa', 'sa?']],
    phonetics: ['keh', 'pah', 'sah'],
    definition: "what's up?",
    explanation: "A phrase that translates to 'what's up?'",
  },
  {
    id: 'phrase40',
    type: 'Generic',
    phrase: [['ma', 'jo']],
    phonetics: ['mah', 'ho'],
    definition: 'pleasant / attractive',
    explanation: "This one is a way of saying something is 'pleasant' or 'attractive'",
  },
]
