image: alpine

variables:
  APP_NAME: 'madri-excepcional-conectada'
  GIT_SUBMODULE_STRATEGY: recursive
  GIT_SUBMODULE_FORCE_HTTPS: true

stages:
  - deploy

before_script:
  - apk add --no-cache curl bash git
  - rm -rf .ci && mkdir -p .ci
  - git submodule sync
  - git submodule update --init --recursive
  - curl -L https://fly.io/install.sh | sh
  - export PATH="$HOME/.fly/bin:$PATH"
  - export FLY_ACCESS_STG_TOKEN=$FLY_API_STG_TOKEN
  - export FLY_ACCESS_PRD_TOKEN=$FLY_API_PRD_TOKEN

stg_deploy:
  script:
    - 'fly deploy -a se-stg-${APP_NAME} -c .ci/fly.toml --dockerfile .ci/Dockerfile --build-arg IOTT_NODE_ENV=stg --update-only --now --process-groups app --yes -t ${FLY_ACCESS_STG_TOKEN}'
  stage: deploy
  only:
    - staging

prd_deploy:
  script:
    - 'fly deploy -a se-prd-${APP_NAME} -c .ci/fly.toml --dockerfile .ci/Dockerfile --build-arg IOTT_NODE_ENV=prd --update-only --now --process-groups app --yes -t ${FLY_ACCESS_PRD_TOKEN}'
  stage: deploy
  only:
    - master
    - main
